name: budget-rag
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.10
  - pip=24.3.1
  - pip:
    - llama-index==0.12.1
    - llama-index-llms-openai==0.3.1
    - pydantic==2.9.2
    - streamlit==1.40.1
